exclude: 
  - README.md
  - Dockerfile
  - '*.yml'
  - '*.yaml'
permalink: pretty
title: ''

google_analytics_id: "G-06888T50J0"
homepage:
  show_call_box: false
logo:
  mobile: "images/logo/wisl.svg"
  desktop: "images/logo/wisl.svg"
  desktop_height: "80px"
footer:
  copyright_text: '© WISL 🌎'

seo:
  meta_og_title: "WISL"
  meta_og_type: "website"
  meta_og_url: "https://wisl.earth"
  meta_og_description: ""

collections:
  services:
    output: false
  team:
    output: false
    
sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10
